---
- name: CVP_Test
  gather_facts: no
  connection: local
  hosts: cvpapln
  vars_files:
    - vars/lab_data.yml
  tasks:
    - name: CV_FACTS
      cv_facts:
        host: "{{ansible_host}}"
        username: "{{username}}"
        password: "{{password}}"
      register: cvp_facts
    - name: CV_CONFIGLET
      cv_configlet:
        host: "{{ansible_host}}"
        username: "{{username}}"
        password: "{{password}}"
        cvp_facts: "{{cvp_facts}}"
        configlets: "{{configlets}}"
        configlet_filter: ["Test","base-chk","base-firewall"]
      check_mode: no
      register: cvp_configlet
    - debug:
        var: cvp_configlet
    - name: CV_DEVICE
      cv_device:
        host: "{{ansible_host}}"
        username: "{{username}}"
        password: "{{password}}"
        cvp_facts: "{{cvp_facts}}"
        devices: "{{devices}}"
        device_filter: ["all"]
      check_mode: no
      register: cvp_device
    - debug:
        var: cvp_device
